# Generated by Django 5.2.8 on 2025-11-23 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('current_city', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=100)),
                ('preferred_languages', models.JSONField(default=list, help_text='List of preferred languages')),
                ('current_status', models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate')], max_length=50)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('stream_specialization', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('academic_scores', models.CharField(help_text='CGPA/Percentage', max_length=50)),
                ('has_backlogs', models.BooleanField(default=False)),
                ('num_backlogs', models.IntegerField(default=0)),
                ('english_speaking', models.IntegerField(default=1, help_text='1-5 rating')),
                ('english_reading', models.IntegerField(default=1, help_text='1-5 rating')),
                ('english_writing', models.IntegerField(default=1, help_text='1-5 rating')),
                ('computer_skills', models.JSONField(default=list, help_text='List of computer skills')),
                ('tool_exposure', models.JSONField(default=list, help_text='List of tools known')),
                ('typing_speed', models.IntegerField(default=0, help_text='WPM')),
                ('preferred_job_roles', models.JSONField(default=list, help_text='Priority-ranked list of job roles')),
                ('preferred_industries', models.JSONField(default=list, help_text='List of preferred industries')),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('office', 'Office'), ('hybrid', 'Hybrid'), ('any', 'Any')], max_length=20)),
                ('preferred_locations', models.JSONField(default=list, help_text='List of preferred work locations')),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('expected_salary', models.CharField(max_length=50)),
                ('time_for_training', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends Only')], max_length=50)),
                ('preferred_time_slots', models.JSONField(default=list, help_text='Preferred training time slots')),
                ('has_mobile_access', models.BooleanField(default=True)),
                ('has_laptop_access', models.BooleanField(default=False)),
                ('internet_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('constraints', models.TextField(blank=True, help_text='Any constraints or limitations')),
                ('comfort_talking_strangers', models.IntegerField(default=3)),
                ('comfort_handling_angry_customers', models.IntegerField(default=3)),
                ('comfort_working_with_data', models.IntegerField(default=3)),
                ('comfort_following_targets', models.IntegerField(default=3)),
                ('comfort_writing_emails', models.IntegerField(default=3)),
                ('people_vs_task_oriented', models.CharField(choices=[('people', 'People-oriented'), ('task', 'Task-oriented')], max_length=20)),
                ('office_vs_remote', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote')], max_length=20)),
                ('analysis_vs_communication', models.CharField(choices=[('analysis', 'Analysis'), ('communication', 'Communication')], max_length=20)),
                ('career_concerns', models.JSONField(default=list, help_text='List of career concerns')),
                ('career_goal_3_years', models.TextField(help_text='Career goal in 3 years (3-4 lines)')),
                ('previous_training', models.TextField(blank=True, help_text='Details of previous training')),
                ('discovery_source', models.CharField(help_text='How did you find us', max_length=100)),
                ('commitment_confirmed', models.BooleanField(default=False)),
                ('fee_preference', models.CharField(choices=[('upfront', 'Pay Upfront'), ('emi', 'EMI'), ('free', 'Free Program'), ('scholarship', 'Scholarship')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='marksheets/')),
                ('step_completed', models.IntegerField(default=0, help_text='Last completed step (0-8)')),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('duration', models.CharField(help_text='e.g., 6 months, 1 year', max_length=100)),
                ('description', models.TextField(help_text='Brief description of responsibilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'db_table': 'experiences',
                'ordering': ['-created_at'],
            },
        ),
    ]
