# Generated by Django 5.2.8 on 2025-11-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
