# Generated by Django 5.2.8 on 2025-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='analysis_vs_communication',
            field=models.CharField(blank=True, choices=[('analysis', 'Analysis'), ('communication', 'Communication')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='office_vs_remote',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='people_vs_task_oriented',
            field=models.CharField(blank=True, choices=[('people', 'People-oriented'), ('task', 'Task-oriented')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_languages',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred languages', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stream_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='work_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('office', 'Office'), ('hybrid', 'Hybrid'), ('any', 'Any')], max_length=20, null=True),
        ),
    ]
