# Generated by Django 5.2.8 on 2025-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_analysis_vs_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
